---

- name: restart docker-registry
  service: name=docker-registry state=restarted

- name: restart registry
  shell: docker restart registry

- name: restart nginx
  service: name=nginx state=restarted
