---
# Notes :
# It is possible to use cspicer.ansible-docker ansible role to install Docker on Debian Jessie
# via the official Docker Ubuntu apt repository.

# docker-py doesn't autodetect the api version of the server it's connecting to and adjust 
# itself accordingly. For people running ansible this means that you could have a mismatch 
# between docker-py and the docker server where docker-py's default ApiVersion is different
# than the docker server's ApiVersion. Specifying 'docker_api_version' for your task fix things.

- name: Install docker.io package
  apt: name=docker.io={{ docker_deb_package_version }} state=present

- name: Make sure docker is running
  service:
    name: docker
    state: started

- name: Copy the default Docker configuration
  template: src=docker.default dest=/etc/default/docker owner=root group=root mode=0644
  notify: restart docker
  when: daemon_start_options != ""

# You can add users to the docker group to allow them to manage docker containers.
- name: Add vagrant user to docker group
  user: name=vagrant groups=docker append=yes

- name: Install some python packages
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - python-dev
    - python-setuptools

# Use easy_install to install pip instead of installling python-pip package which seems to be buggy.
# On Debian Jessie (stable distro now) python-pip=1.5.6-5 pip throws errors.
- name: Install pip
  command: easy_install pip

- name: Install docker-py
  pip: name=docker-py version={{ docker_py_version }}
