---

- name: Create a tmp directory to generate openssl certs/keys
  local_action: file path=./ssl state=directory
  sudo: no

- name: Check if a local certificate exists already
  local_action: stat path=ssl/docker-registry.crt
  register: local_certificate
  sudo: no

- name: Create server key and certificate
  local_action: shell /bin/bash --login -c 'openssl req -new -nodes -x509 -subj "/C=/ST=/L=/O=/CN={{registry_fqdn}}/subjectAltName=IP:{{registry_ip}}" -days 3650 -keyout ./ssl/docker-registry.key -out ./ssl/docker-registry.crt -extensions v3_ca'
  sudo: no
  when: not local_certificate.stat.exists

- name: Copy the certificate to Nginx config
  copy: src=./ssl/{{item}} dest="{{ nginx_certs_dir }}"
  with_items:
    - docker-registry.key
    - docker-registry.crt

- name: Copy the certificate to the shared ca-certificates directory
  copy: src=./ssl/docker-registry.crt dest=/usr/local/share/ca-certificates/{{registry_fqdn}}.crt

- name: Update ca-certificates list
  shell: update-ca-certificates

- name: Create a directory to hold the cert on Docker
  file: path=/etc/docker/certs.d/{{registry_fqdn}} state=directory

- name: Copy the certificate to Docker config
  copy: src=./ssl/docker-registry.crt dest=/etc/docker/certs.d/{{registry_fqdn}}/ca.crt
  notify: restart docker
