---
- hosts: cip-vm
  sudo: true
  tasks:
    - name: Create ext3 filesystem on /dev/sdb
      filesystem: fstype=ext3 dev=/dev/sdb
    - name: Mount /dev/sdb
      mount: name=/data src=/dev/sdb fstype=ext3 state=mounted
